export const mockTransparencyData = {
  reports: [
    {
      month: "জুন ২০২৬",
      monthEn: "June 2026",
      totalDonation: 85000,
      totalExpense: 62000,
      computersBought: 2,
      studentsTrained: 8,
      summary:
        "এই মাসে ২টি নতুন Refurbished Desktop ক্রয় করা হয়েছে এবং ৮ জন শিক্ষার্থীকে বেসিক কম্পিউটার ট্রেনিং দেওয়া হয়েছে।",
      status: "published",
    },
    {
      month: "মে ২০২৬",
      monthEn: "May 2026",
      totalDonation: 45000,
      totalExpense: 38000,
      computersBought: 1,
      studentsTrained: 5,
      summary:
        "১টি ল্যাপটপ ক্রয় এবং ইন্টারনেট সংযোগ স্থাপন করা হয়েছে। ৫ জন নতুন শিক্ষার্থী যোগ দিয়েছে।",
      status: "published",
    },
    {
      month: "এপ্রিল ২০২৬",
      monthEn: "April 2026",
      totalDonation: 30000,
      totalExpense: 25000,
      computersBought: 1,
      studentsTrained: 3,
      summary:
        "প্রথম কম্পিউটার ল্যাপটপ ক্রয় এবং ক্লাসরুম সেটআপ শুরু করা হয়েছে।",
      status: "published",
    },
  ],
  expenses: [
    {
      date: "১৫ জুন ২০২৬",
      dateEn: "15 June 2026",
      item: "Refurbished Desktop (HP)",
      category: "Equipment",
      amount: 18000,
      invoiceNo: "INV-2026-003",
      vendor: "Computer Bazar, Dhaka",
    },
    {
      date: "১০ জুন ২০২৬",
      dateEn: "10 June 2026",
      item: "Keyboard + Mouse (5 Sets)",
      category: "Accessories",
      amount: 5000,
      invoiceNo: "INV-2026-002",
      vendor: "Star Tech",
    },
    {
      date: "০৫ জুন ২০২৬",
      dateEn: "05 June 2026",
      item: "Internet Bill (3 Months)",
      category: "Utility",
      amount: 4500,
      invoiceNo: "INV-2026-001",
      vendor: "Banglalion",
    },
    {
      date: "২০ মে ২০২৬",
      dateEn: "20 May 2026",
      item: "Used Monitor (Dell 22 inch)",
      category: "Equipment",
      amount: 12000,
      invoiceNo: "INV-2026-000",
      vendor: "IDB Computer Market",
    },
  ],
  photos: [
    {
      title: "কম্পিউটার ক্লাস শুরু",
      titleEn: "Computer Class Started",
      date: "১২ জুন ২০২৬",
      description: "আমাদের প্রথম কম্পিউটার ক্লাস শুরু হলো। শিক্ষার্থীরা উৎসাহের সাথে অংশ নিচ্ছে।",
      src: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1000&auto=format&fit=crop",
    },
    {
      title: "নতুন ল্যাপটপ হস্তান্তর",
      titleEn: "New Laptop Handover",
      date: "০৫ জুন ২০২৬",
      description: "দাতারা নতুন ল্যাপটপ হস্তান্তর করছেন অনাথ আশ্রমের কর্তৃপক্ষের কাছে।",
      src: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=1000&auto=format&fit=crop",
    },
    {
      title: "শিক্ষার্থীদের সাথে সাক্ষাৎ",
      titleEn: "Meeting with Students",
      date: "২০ মে ২০২৬",
      description: "স্বেচ্ছাসেবকরা শিক্ষার্থীদের সাথে কথা বলছেন এবং তাদের আগ্রহ জানছেন।",
      src: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=1000&auto=format&fit=crop",
    },
    {
      title: "কম্পিউটার ল্যাব সেটআপ",
      titleEn: "Computer Lab Setup",
      date: "১০ মে ২০২৬",
      description: "অনাথ আশ্রমে কম্পিউটার ল্যাব সেটআপের কাজ চলছে।",
      src: "https://images.unsplash.com/photo-1529390079861-5919fd96830d?q=80&w=1000&auto=format&fit=crop",
    },
  ],
  invoices: [
    {
      invoiceNo: "INV-2026-003",
      date: "১৫ জুন ২০২৬",
      dateEn: "15 June 2026",
      vendor: "Computer Bazar, Dhaka",
      items: "Refurbished Desktop (HP) x1",
      amount: 18000,
      status: "paid",
    },
    {
      invoiceNo: "INV-2026-002",
      date: "১০ জুন ২০২৬",
      dateEn: "10 June 2026",
      vendor: "Star Tech",
      items: "Keyboard + Mouse (5 Sets)",
      amount: 5000,
      status: "paid",
    },
    {
      invoiceNo: "INV-2026-001",
      date: "০৫ জুন ২০২৬",
      dateEn: "05 June 2026",
      vendor: "Banglalion",
      items: "Internet Bill (3 Months)",
      amount: 4500,
      status: "paid",
    },
    {
      invoiceNo: "INV-2026-000",
      date: "২০ মে ২০২৬",
      dateEn: "20 May 2026",
      vendor: "IDB Computer Market",
      items: "Used Monitor (Dell 22 inch) x1",
      amount: 12000,
      status: "paid",
    },
  ],
  equipment: [
    {
      name: "Refurbished Desktop (HP)",
      specs: "Intel i3, 8GB RAM, 256GB SSD",
      quantity: 4,
      condition: "Good",
      donatedBy: "Digital Future Initiative Fund",
      date: "জুন ২০২৬",
    },
    {
      name: "Used Monitor (Dell 22 inch)",
      specs: "Full HD, LED Display",
      quantity: 5,
      condition: "Good",
      donatedBy: "Digital Future Initiative Fund",
      date: "মে-জুন ২০২৬",
    },
    {
      name: "Keyboard + Mouse",
      specs: "USB Wired, Standard",
      quantity: 10,
      condition: "New",
      donatedBy: "Individual Donors",
      date: "জুন ২০২৬",
    },
    {
      name: "Laptop (Lenovo ThinkPad)",
      specs: "Intel i5, 8GB RAM, 512GB SSD",
      quantity: 2,
      condition: "Excellent",
      donatedBy: "Mr. Rahman (Donor)",
      date: "এপ্রিল ২০২৬",
    },
    {
      name: "Projector",
      specs: "Epson, 3000 Lumens",
      quantity: 1,
      condition: "Good",
      donatedBy: "Sanatani SSC 91",
      date: "মার্চ ২০২৬",
    },
  ],
  drive: {
    url: "https://drive.google.com/drive/folders/example",
    folders: [
      { name: "Monthly Reports (PDF)", count: 3 },
      { name: "Expense Invoices", count: 12 },
      { name: "Activity Photos", count: 48 },
      { name: "Student Progress Sheets", count: 8 },
      { name: "Equipment Bills", count: 5 },
    ],
    lastUpdated: "২৫ জুন ২০২৬",
  },
};
